"""add_currency_to_assets

Revision ID: 04fa44e8d563
Revises: 08d5318baffb
Create Date: 2026-01-31 22:33:11.935320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04fa44e8d563'
down_revision: Union[str, Sequence[str], None] = '08d5318baffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add column as nullable
    op.add_column('unified_assets', sa.Column('currency', sa.String(), nullable=True))
    
    # 2. Set default value for existing rows
    op.execute("UPDATE unified_assets SET currency = 'USD' WHERE currency IS NULL")
    
    # 3. Alter column to be NOT NULL
    op.alter_column('unified_assets', 'currency', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unified_assets', 'currency')
    # ### end Alembic commands ###
