"""add_image_url_to_assets

Revision ID: 08d5318baffb
Revises: 224ec1c73ddd
Create Date: 2026-01-31 11:15:30.266852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08d5318baffb'
down_revision: Union[str, Sequence[str], None] = '224ec1c73ddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unified_assets', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unified_assets', 'image_url')
    # ### end Alembic commands ###
