"""add_snapshots_and_usd_value.

Revision ID: 1aa41f4fff5d
Revises: a5f7da2cb685
Create Date: 2026-01-17 17:17:52.196697

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1aa41f4fff5d"
down_revision: Union[str, Sequence[str], None] = "a5f7da2cb685"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "portfolio_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("total_value_usd", sa.Numeric(precision=30, scale=8), nullable=False),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_portfolio_snapshots_user_id"), "portfolio_snapshots", ["user_id"], unique=False)
    op.add_column("unified_assets", sa.Column("usd_value", sa.Numeric(precision=30, scale=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("unified_assets", "usd_value")
    op.drop_index(op.f("ix_portfolio_snapshots_user_id"), table_name="portfolio_snapshots")
    op.drop_table("portfolio_snapshots")
    # ### end Alembic commands ###
