"""Add ISIN column to UnifiedAsset

Revision ID: 24691d2b4cc7
Revises: 3368a384d4e4
Create Date: 2026-02-24 10:39:08.185198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24691d2b4cc7'
down_revision: Union[str, Sequence[str], None] = '3368a384d4e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unified_assets', sa.Column('isin', sa.String(), nullable=True))
    op.create_index(op.f('ix_unified_assets_isin'), 'unified_assets', ['isin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unified_assets_isin'), table_name='unified_assets')
    op.drop_column('unified_assets', 'isin')
    # ### end Alembic commands ###
