"""Add unified_assets and portfolio_aggregates tables

Revision ID: a5f7da2cb685
Revises: add_integrations_001
Create Date: 2026-01-16 22:25:47.303106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5f7da2cb685'
down_revision: Union[str, Sequence[str], None] = 'add_integrations_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_aggregates',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('weighted_avg_price', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'symbol')
    )
    op.create_index(op.f('ix_portfolio_aggregates_symbol'), 'portfolio_aggregates', ['symbol'], unique=False)
    op.create_index(op.f('ix_portfolio_aggregates_user_id'), 'portfolio_aggregates', ['user_id'], unique=False)
    op.create_table('unified_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('integration_id', sa.UUID(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('asset_type', sa.Enum('CRYPTO', 'STOCK', 'FIAT', name='assettype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unified_assets_id'), 'unified_assets', ['id'], unique=False)
    op.create_index(op.f('ix_unified_assets_integration_id'), 'unified_assets', ['integration_id'], unique=False)
    op.create_index(op.f('ix_unified_assets_symbol'), 'unified_assets', ['symbol'], unique=False)
    op.create_index(op.f('ix_unified_assets_user_id'), 'unified_assets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unified_assets_user_id'), table_name='unified_assets')
    op.drop_index(op.f('ix_unified_assets_symbol'), table_name='unified_assets')
    op.drop_index(op.f('ix_unified_assets_integration_id'), table_name='unified_assets')
    op.drop_index(op.f('ix_unified_assets_id'), table_name='unified_assets')
    op.drop_table('unified_assets')
    op.drop_index(op.f('ix_portfolio_aggregates_user_id'), table_name='portfolio_aggregates')
    op.drop_index(op.f('ix_portfolio_aggregates_symbol'), table_name='portfolio_aggregates')
    op.drop_table('portfolio_aggregates')
    # ### end Alembic commands ###
