"""add_market_price_history

Revision ID: c3c2775a8420
Revises: 04fa44e8d563
Create Date: 2026-02-02 10:48:46.142626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3c2775a8420'
down_revision: Union[str, Sequence[str], None] = '04fa44e8d563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_price_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_price_history_provider_id'), 'market_price_history', ['provider_id'], unique=False)
    op.create_index(op.f('ix_market_price_history_symbol'), 'market_price_history', ['symbol'], unique=False)
    op.create_index(op.f('ix_market_price_history_timestamp'), 'market_price_history', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_price_history_timestamp'), table_name='market_price_history')
    op.drop_index(op.f('ix_market_price_history_symbol'), table_name='market_price_history')
    op.drop_index(op.f('ix_market_price_history_provider_id'), table_name='market_price_history')
    op.drop_table('market_price_history')
    # ### end Alembic commands ###
